kind: pipeline
type: docker
name: gotil

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: mysql
    pull: if-not-exists
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "school"
    detach: true

  - name: ci_1.13
    pull: if-not-exists
    image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...
    depends_on:
      - mysql

  - name: ci_1.14
    pull: if-not-exists
    image: golang:1.14
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...
    depends_on:
      - mysql

  - name: ci_1.15
    pull: if-not-exists
    image: golang:1.15
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn,direct"
      GOSUMDB: "off"
      CGO_ENABLED: "0"
      GOOS: "linux"
    commands:
      - go version
      - go env
      - go mod tidy
      - go test ./...
    depends_on:
      - mysql

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
    - tag
